// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGyH19rIjhJgn45VJjrjUEbLmiCOHTMRI',
    appId: '1:1042697993335:web:867be1eb4aaaaceb38da72',
    messagingSenderId: '1042697993335',
    projectId: 'social-media-app-f30e3',
    authDomain: 'social-media-app-f30e3.firebaseapp.com',
    storageBucket: 'social-media-app-f30e3.appspot.com',
    measurementId: 'G-DH8T2GSBQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdHdJp1z0ddlGgsLe8tmkvcIn-amnRjd4',
    appId: '1:1042697993335:android:f8bacfac838b039338da72',
    messagingSenderId: '1042697993335',
    projectId: 'social-media-app-f30e3',
    storageBucket: 'social-media-app-f30e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd1ftGxyJZBC4TzhVDcqXBK3PgRnkX5vA',
    appId: '1:1042697993335:ios:6a5dc6ef587e682238da72',
    messagingSenderId: '1042697993335',
    projectId: 'social-media-app-f30e3',
    storageBucket: 'social-media-app-f30e3.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
